services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    
  api:
    build:
      context: ./aws-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
